# Generated by Django 6.0.2 on 2026-02-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Внутреннее название для идентификации меню', max_length=255, verbose_name='Название меню')),
                ('slug', models.SlugField(help_text="Уникальный идентификатор для использования в шаблонах (например, 'main_menu')", max_length=255, unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(default=True, help_text='Если отключено, меню не будет отображаться на сайте', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('page', 'Страница сайта'), ('custom', 'Внешний URL'), ('anchor', 'Якорная ссылка')], default='page', help_text='Выберите тип ссылки: страница, внешний URL или якорь', max_length=20, verbose_name='Тип ссылки')),
                ('title', models.CharField(blank=True, help_text='Текст пункта меню. Если не указан, будет использован заголовок страницы', max_length=255, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, help_text="Внешний URL (например, 'https://example.com') или якорь (например, '#contacts' или '/page#anchor')", max_length=500, verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Открывать ссылку в новой вкладке/окне', verbose_name='Открывать в новой вкладке')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='site_menu.menu', verbose_name='Меню')),
                ('page', models.ForeignKey(blank=True, help_text="Выберите страницу Wagtail для ссылки (для типа 'Страница сайта')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Страница')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите родительский пункт для создания подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='site_menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
